// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login/email": {
            "post": {
                "description": "login by email/password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "login by email",
                "parameters": [
                    {
                        "description": "login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/password_http.LoginByEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/password_http.LoginByEmailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/password_http.LoginBadRequestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/password_http.LoginInternalError"
                        }
                    }
                }
            }
        },
        "/auth/register/email": {
            "post": {
                "description": "Creates a new user account using email/password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register by email",
                "parameters": [
                    {
                        "description": "Register payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/password_http.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/password_http.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/password_http.RegisterBadRequestError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/password_http.RegisterConflictError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/password_http.RegisterInternalError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "password_http.LoginBadRequestError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "enum": [
                        "invalid_json",
                        "email_required",
                        "password_required",
                        "invalid_email",
                        "invalid_credentials"
                    ],
                    "example": "invalid_credentials"
                },
                "message": {
                    "type": "string",
                    "example": "invalid email or password"
                }
            }
        },
        "password_http.LoginByEmailRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "password_http.LoginByEmailResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "password_http.LoginInternalError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "enum": [
                        "internal_error"
                    ],
                    "example": "internal_error"
                },
                "message": {
                    "type": "string",
                    "example": "internal error"
                }
            }
        },
        "password_http.RegisterBadRequestError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "enum": [
                        "invalid_json",
                        "email_required",
                        "password_required",
                        "invalid_email",
                        "password_too_short",
                        "password_too_long",
                        "password_no_letter",
                        "password_no_digit",
                        "password_no_upper_letter"
                    ],
                    "example": "password_too_short"
                },
                "message": {
                    "type": "string",
                    "example": "password too short"
                }
            }
        },
        "password_http.RegisterConflictError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "enum": [
                        "email_already_exists"
                    ],
                    "example": "email_already_exists"
                },
                "message": {
                    "type": "string",
                    "example": "email already exists"
                }
            }
        },
        "password_http.RegisterInternalError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "enum": [
                        "internal_error"
                    ],
                    "example": "internal_error"
                },
                "message": {
                    "type": "string",
                    "example": "internal error"
                }
            }
        },
        "password_http.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "password_http.RegisterResponse": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1/",
	Schemes:          []string{"http"},
	Title:            "Auth API",
	Description:      "Financial Intelligence API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
