basePath: /api/v1/
definitions:
  password_http.LoginBadRequestError:
    properties:
      code:
        enum:
        - invalid_json
        - email_required
        - password_required
        - invalid_email
        - invalid_credentials
        example: invalid_credentials
        type: string
      message:
        example: invalid email or password
        type: string
    type: object
  password_http.LoginByEmailRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  password_http.LoginByEmailResponse:
    properties:
      status:
        type: string
    type: object
  password_http.LoginInternalError:
    properties:
      code:
        enum:
        - internal_error
        example: internal_error
        type: string
      message:
        example: internal error
        type: string
    type: object
  password_http.RegisterBadRequestError:
    properties:
      code:
        enum:
        - invalid_json
        - email_required
        - password_required
        - invalid_email
        - password_too_short
        - password_too_long
        - password_no_letter
        - password_no_digit
        - password_no_upper_letter
        example: password_too_short
        type: string
      message:
        example: password too short
        type: string
    type: object
  password_http.RegisterConflictError:
    properties:
      code:
        enum:
        - email_already_exists
        example: email_already_exists
        type: string
      message:
        example: email already exists
        type: string
    type: object
  password_http.RegisterInternalError:
    properties:
      code:
        enum:
        - internal_error
        example: internal_error
        type: string
      message:
        example: internal error
        type: string
    type: object
  password_http.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  password_http.RegisterResponse:
    properties:
      userID:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Financial Intelligence API
  title: Auth API
  version: "1.0"
paths:
  /auth/login/email:
    post:
      consumes:
      - application/json
      description: login by email/password
      parameters:
      - description: login payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/password_http.LoginByEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/password_http.LoginByEmailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/password_http.LoginBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/password_http.LoginInternalError'
      summary: login by email
      tags:
      - Auth
  /auth/register/email:
    post:
      consumes:
      - application/json
      description: Creates a new user account using email/password
      parameters:
      - description: Register payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/password_http.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/password_http.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/password_http.RegisterBadRequestError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/password_http.RegisterConflictError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/password_http.RegisterInternalError'
      summary: Register by email
      tags:
      - Auth
schemes:
- http
swagger: "2.0"
